### ISSUE TITLE
Template objects should be overwritable or intelligently updated

### ISSUE THREAD

**Issue by litzebauer** [gonzofish/erector-set#3]
To resolve gonzofish/angular-library-set#4 I think template objects should have 2 optional boolean properties on them.  "overwrite" "update"

- *overwrite* would just overwrite the file
- *update* would be used for json files where we intelligently parse the keys from the templates file and put them in the existing json file.  Think package.json

I think the processing for this should be done in the erector-set project in construct so that all users of erector-set get this feature

**Comment by gonzofish** [comment]
Totally agree with this. I know we're moving into the territory of duplicating the efforts of other projects (ie, yeoman), but as we do this, just keep in mind the aim of this is to be lightweight, without dependencies...
